import Header from "./(components)/Navbar/page"
import './global.css'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
 return (
    <html lang="en">
      
      <body>
      <header>
    <Header/>
      </header>
        {children}
        
        </body>
    </html>
  )
}
